trainer:
  mode: 'train'
  output_dir: "/grogu/user/akirchme/multiview/checkpoints/views5-mae"
  logging_dir: 'logs'
  mixed_precision: "no"
  use_8bit_adam: True
  train_batch_size: 4
  total_batch_size: 8
  gradient_accumulation_steps: 2
  num_train_epochs: 50
  checkpointing_epochs: 10
  resume_from_checkpoint: 'latest'
  set_grads_to_none: True
  enable_xformers_memory_efficient_attention: False
  gradient_checkpointing: False
  seed: null
  dataloader_num_workers: 8
  max_grad_norm: 1.0
  num_eval: 3
  num_latents: 3
  res: 16



optimizer:
  learning_rate: 5e-6
  scale_lr: False
  lr_scheduler: "polynomial"
  lr_warmup_steps: 500
  lr_num_cycles: 1
  lr_power: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-2
  adam_epsilon: 1e-08

diffusion:
  sd_model: "stabilityai/stable-diffusion-2-1-base"
  train_multiview_encoder: False
  with_prior_preservation: False
  prior_loss_weight: None

multiview_encoder:
  model_name: 'mae'
  model_size: 'large'
  view_mask_ratio: 0.75
  dropout: 0.2
  cross_attention_dim: 1024
  pose_emb_dim: 20

  mae:
    model_checkpoint_path: "/grogu/user/akirchme/pretrained/mae"
    resolution: 224
    image_mask_ratio: 0.75

dataset:
  train_subsample_inst_size: 10
  val_subsample_inst_size: 1
  resolution: 512
  context_resolution: 224
  num_images: 1000
  img_data_path: "/grogu/user/akirchme/art3d_sd_webui/fg/dog"
  depth_data_path: "/grogu/user/akirchme/art3d_sd_webui/depth/dog"
  view_data_path: "/grogu/user/akirchme/art3d_sd_webui/multiview_new/dog/novel_view_rgb"
  mask_data_path: "/grogu/user/akirchme/art3d_sd_webui/masks/dog"
  meta_data_file: "/grogu/user/akirchme/art3d_sd_webui/metadata_new/dog/multiview_0_300.csv"
  center_crop: False
  random_flip: False
  cls: 'dog'
