sd_model: "stabilityai/stable-diffusion-2-1-base"
output_dir: "/grogu/user/akirchme/multiview/checkpoints/views10"
train_multiview_encoder: False
with_prior_preservation: False
mixed_precision: "no"
use_8bit_adam: True
train_batch_size: 4
img_data_path: "/grogu/user/akirchme/art3d_sd_webui/multiview/horse"
meta_data_file: "/grogu/user/akirchme/art3d_sd_webui/metadata/horse/multiview.csv"
mae_checkpoint_path: "/grogu/user/akirchme/pretrained/mae"
resolution: 512
num_train_epochs: 5

mae_resolution: 224
n_views_per_inst: 10
image_mask_ratio: 0.75
view_mask_ratio: 0.75
model_size: 'large'

logging_dir: 'logs'
resume_from_checkpoint: 'latest'
gradient_accumulation_steps: 1
set_grads_to_none: False
checkpointing_steps: 5000
max_train_steps: null
report_to: 'wandb'
enable_xformers_memory_efficient_attention: False
gradient_checkpointing: False
seed: null


learning_rate: 5e-6
scale_lr: False
lr_scheduler: "polynomial"
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
dataloader_num_workers: 8
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-2
adam_epsilon: 1e-08
max_grad_norm: 1.0

center_crop: False